### PR TITLE
Updated Twee 3 specification

### PR DESCRIPTION
**Pull request by tmedwards**
Updated Twee 3 specification to:

* Include additional details and compiler requirements about IFIDs.
* Address ambiguity around escapement.

Version bumped to v3.0.1.

@klembot @videlais @mcdemarco @greyelf @tmedwards

### CODE REVIEW

**Comment by tmedwards** [comment]
Aye.

**Comment by videlais** [comment]
Aye

**Comment by mcdemarco** [comment]
Aye.

**Comment by tmedwards** [comment]
Amended the PR to address ambiguity around escapement.  Issue was brought up on the Twine Games Discord.

**Pull request merged**
